title: YueHao Chen's Homepage
page-top-title: YueHao Chen
top-section-bg-text: Data Science and Big Data Technology
home-subtitle: YueHao Chen&ensp;|&ensp;陈岳豪
copyright-text: '&copy; YueHao Chen 2023-2026. All Rights Reserved.'
